### ISSUE TITLE
Fail to sign transaction in Android browser

### ISSUE THREAD

**Issue by arthew** [ethereumjs/browser-builds#1]
Case Scenario:
call tx.sign method in Android Smart Phone, exception raised: has no method 'assign' as:
![542763705](https://cloud.githubusercontent.com/assets/6278979/14906787/1c6dab88-0df2-11e6-8f0d-81f59bddabfd.jpg)

it works on desktop and IOS.

**Comment by arthew** [comment]
Addition Comments：
On Andorid mobile, it runs OK in Chrome browser, but others NOT

**Comment by arthew** [comment]
**Root Cause located**
in function transaction.sign, new feature of ECMAScript5 used - Object.assign, which had not been supported in other brower.
Suggest set object's attribute directlly hear.

**Comment by axic** [comment]
@arthew all ethereumjs projects have decided to require ES6 as a minimum. Please include es6-shim in your project. This should be more clearer and addressed in the documentation.

Hope this helps?

**Comment by arthew** [comment]
Yes, thanks. It runs OK with es6-shim included.
