### ISSUE TITLE
Disable source mapping or create it as a separate file

### ISSUE THREAD

**Issue by axic** [ethereumjs/browser-builds#10]
For example it takes up almost half of the 7Mbs of this file: https://raw.githubusercontent.com/ethereumjs/browser-builds/master/dist/ethereumjs-vm/ethereumjs-vm-2.3.1.js

I think it used to be much smaller before the switch in the build system due to not including the source mapping.

**Comment by holgerd77** [comment]
Hmm, that's why I created two different files, one minified version without and a plain source version with the source maps. I actually like source maps for debugging. Is there any reason the non-minified version should be optimized in space? Or should I add a third build version as another option?

**Comment by axic** [comment]
I think that makes sense - can you please document it in the readme so it is apparent?

**Comment by holgerd77** [comment]
Yes, will do, will just add that to the PR I just opened.
