### ISSUE TITLE
Firefox 48.0 ethereum-tx ethUtil.pubToAddress bug in Buffer.slice

### ISSUE THREAD

**Issue by ArtemKo7v** [ethereumjs/browser-builds#3]
Browser: Firefox 48.0
OS: Windows 7, Windows 8.1

```
var address = ethUtil.pubToAddress("0x045614e693becd6b8cdcb393a9529e44c73f73c3416e623f5bd0e07c57cb49ad30142a77b9545c8cb49350354324a9b24479d7bc322484c5fc9ee3b79343445f92");
console.log(address);
// returns string "[object Object]"
```

**Comment by axic** [comment]
@ArtemKo7v the address is a `Buffer`, you need to use `toString('hex')` on it.

**Comment by ArtemKo7v** [comment]
> @ArtemKo7v the address is a Buffer, you need to use toString('hex') on it.

Yes, and I am axpecting it to be a Buffer.
But since FF 48.0 it returns "undefined" and prints a string "[object Object]" in browser console.
Was working in previous versions of Firefox, broken today after FF updated.

The same prolem with ethUtil.privateToAddress function.
See the image below.

[http://i.imgur.com/akvOooO.png](http://i.imgur.com/akvOooO.png)

P.S. About 15% of our users are using Firefox to access our project, so this issue is very sensitive and important for us. Thank you.

**Comment by ArtemKo7v** [comment]
Looks like the problem is related to a Buffer.slice Firefox problem.

```
> buff = new Buffer('0102030405', 'hex');  // Uint8Array [ 1, 2, 3, 4, 5 ]
> buff.slice(1) // Uint8Array [ 1, 2, 3, 4, 5 ]
```

So, the code below returns invalid value...

```
secp256k1.publicKeyCreate(privateKey, false).slice(1)
```

https://bugzilla.mozilla.org/show_bug.cgi?id=1280052
https://github.com/feross/buffer/issues/120

**Comment by axic** [comment]
@ArtemKo7v thank you for tracking down, uploaded a new build, which uses the latest buffer. Let me know if it works.

**Comment by ArtemKo7v** [comment]
@axic Sorry, still does not work.
The code from this commit (which solves the issue with FF and MS Edge browsers) is missing in your build:
https://github.com/feross/buffer/pull/97/commits/d93a1e2b3326c3c49f579defe43c51559035f077

I also noticed, that in this build ethUtil object is not accessible directly anymore, only through global EthJS object. Not sure if it is a bug or a feature.

**Comment by axic** [comment]
Rebuilt now using browserify@13.1.0 (incl. buffer@4.7.1).

The only exported global should be `EthJS`.

**Comment by ArtemKo7v** [comment]
Works fine now. Thank you.
